log: WARNING
plugins: [ plugins/lib/librd3d_trt_plugin.so ]
engine: config/iassd_hvcsx2_gq_4x8_80e_kitti_3cls(export_fp16).engine
build:
  onnx: config/iassd_hvcsx2_gq_4x8_80e_kitti_3cls(export).onnx
  quan: fp16 # fp32 fp16 int8
  calib: # for int8 build mode
    enable: true
    cache: true
    data: /media/nrsl/NRSL12YEARS/dataset/kitti/data/testing/velodyne
    max_iters: 500

max_batch_size: 1
cls2label:
  1: "Car"
  2: "Pedestrian"
  3: "Cyclist"